### ISSUE TITLE
Issue #1 User can see their car

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML and CSS documents
- [x] create an image element and set the car image as its source.
- [x] create a div container for the car
- [x] set the div to position relative and make sure it covers the entire viewport
- [x] add the color to green to cover the entire page
- [x] give the car an id and set its positioning to absolute
- [x] fix all errors
- [x] remove any unnecessary styling
