### ISSUE TITLE
Issue #2 User can turn their car

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] create a CSS transform functions to position the car in four different directions
- [x] create a css transition to give the car transitions as it turns
- [x] create a main.js file
- [x] query the car in the DOM
- [x] create an event listener for the keydown events
- [x] create a data.js file
- [x] create a data model to hold the information on which way the car is facing
- [x] create a function to update the data model as the car turns
- [x] in the function, update the className properties of the car so it turns according to the keydown events.
- [x] clean up unnecessary code.
- [x] test the app
- [x] fix any bugs
