### ISSUE TITLE
Issue # 3 User can start their car

### ISSUE THREAD

**Issue by RobACurtis** [RobACurtis/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add location to data model to record x and y coordinates on page
- [x] add absolute positioning to img element
- [ ] use the style property to change the top and left box offset styles
- [ ] make sure car moves every 16 milliseconds as it moves
- [ ] check for any bugs
- [ ] clean up unnecessary code
